Bump MSRV to 1.71
```
  error: package `cargo-config2 v0.1.36` cannot be built because it requires rustc 1.71 or newer, while the currently active rustc version is 1.70.0
  Either upgrade to rustc 1.71 or newer, or use
  cargo update -p cargo-config2@0.1.36 --precise ver
  where `ver` is the latest version of `cargo-config2` supporting rustc 1.70.0
```